export const people = [
    {
        name: 'Jane Cooper',
        title: 'Regional Paradigm Technician',
        department: 'Optimization',
        role: 'Admin',
        email: 'jane.cooper@example.com',
        image: 'https://bit.ly/33HnjK0',
        isActive : true,
    },
    {
        name: 'John Doe',
        title: 'Software Testing',
        department: 'Development',
        role: 'Tester',
        email: 'john.doe@example.com',
        image: 'https://bit.ly/3I9nL2D',
        isActive : false,
    },
    {
        name: 'Veronica Lodge',
        title: 'Regional Paradigm Technician',
        department: 'Optimization',
        role: ' Software Engineer',
        email: 'veronica.lodge@example.com',
        image: 'https://bit.ly/3vaOTe1',
        isActive : true,
    },
    {
        name: 'John Wick',
        title: ' Backend Technician',
        department: 'Devops',
        role: ' Software Engineer',
        email: 'wickjohn@example.com',
        image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        isActive : true,
    },
    {
        name: 'Graham Smith',
        title: 'Interviews',
        department: 'Hiring',
        role: 'Recruiter',
        email: 'smith@example.com',
        image: 'https://plus.unsplash.com/premium_photo-1671656349218-5218444643d8?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        isActive : false,
    },
    {
        name: 'Lily Maria',
        title: 'Regional Paradigm Technician',
        department: 'Optimization',
        role: ' Software Engineer',
        email: 'maria.lily@example.com',
        image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        isActive : true,
    },
    {
        name: 'Chadwick Burgman',
        title: 'SDE',
        department: 'Devlopment',
        role: ' Software Devleoper',
        email: 'burgman.Chadwick@example.com',
        image: 'https://images.unsplash.com/photo-1610389372538-90980c897cd3?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        isActive : false,
    },
    {
        name: 'Genie Swift',
        title: 'Recuitment in the company',
        department: 'Hiring',
        role: 'HR',
        email: 'swift@example.com',
        image: 'https://images.unsplash.com/photo-1573878737226-4f9572c22b69?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        isActive : true,
    },
  // More people...
];